### ISSUE TITLE
Third test fails

### ISSUE THREAD

**Issue by cnaw** [HengyueZ/astrofix#1]
Hi @HengyueZ , nice routine, and thanks for making it public. I was able to run it through the notebook, but not on the command line. I had to make some small fixes because the path is hard coded for windows (I assume) with "\\", while in Linux it should be "/"; I also changed the spaces on file names to underscores so there is no confusion with the names. 
Once that was done, tests 1 and 2 pass. Test 3 fails, but I have no idea why.

 (astroconda) [cnaw@tangara astrofix]$ pytest -sv
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/cnaw/anaconda3/envs/astroconda/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/cnaw/python/astrofix/.hypothesis/examples')
rootdir: /home/cnaw/python/astrofix
plugins: asdf-2.9.0.dev0, arraydiff-0.3, astropy-header-0.1.2, cov-2.12.1, doctestplus-0.10.1, filter-subpackage-0.1.1, mock-3.6.1, openfiles-0.5.0, remotedata-0.3.2, hypothesis-6.14.6
collected 3 items                                                                                                                                                        

astrofix/tests/test_main.py::test_kernel_construction PASSED
astrofix/tests/test_main.py::test_training_results PASSED
astrofix/tests/test_main.py::test_fixing_image FAILED

================================================================================ FAILURES ================================================================================
___________________________________________________________________________ test_fixing_image ____________________________________________________________________________

    def test_fixing_image():
    #    file='astrofix\\tests\\cpt0m407-kb84-20200917-0147-e91.fits.fz'
        file='astrofix/tests/cpt0m407-kb84-20200917-0147-e91.fits.fz'
        test_im= fits.open(file)[1].data
    #    BP_mask=np.loadtxt("astrofix\\tests\\Sample Bad Pixel Mask.gz")
        BP_mask=np.loadtxt("astrofix/tests/Sample_Bad_Pixel_Mask.gz")
        BP_mask=BP_mask.astype(bool)
    #    corr_resi=np.loadtxt("astrofix\\tests\\Sample Residual.gz")
        corr_resi=np.loadtxt("astrofix/tests/Sample_Residual.gz")
        img=test_im.copy()
        img[BP_mask]=np.nan
        fixed_img,para,TS=astrofix.Fix_Image(img,"asnan",max_clip=1)
>       assert np.allclose(fixed_img-test_im,corr_resi)
E       assert False
E        +  where False = <function allclose at 0x7fc922f989e0>((array([[  9.99559307,  23.52208138,   5.86796856, ..., -42.99113846,\n          7.09801674,   6.40728998],\n       [-17....2.19702125],\n       [ 28.43076324,   8.34493828,   8.04320908, ...,   6.46460104,\n          5.92233324,  26.08802223]]) - array([[  9.995593  ,  23.522081  ,   5.8679686 , ..., -42.99114   ,\n          7.0980167 ,   6.40729   ],\n       [-17....     [ 28.430763  ,   8.344938  ,   8.043209  , ...,   6.464601  ,\n          5.9223332 ,  26.088022  ]], dtype=float32)), array([[0., 0., 0., ..., 0., 0., 0.],\n       [0., 0., 0., ..., 0., 0., 0.],\n       [0., 0., 0., ..., 0., 0., 0.],\n       ...,\n       [0., 0., 0., ..., 0., 0., 0.],\n       [0., 0., 0., ..., 0., 0., 0.],\n       [0., 0., 0., ..., 0., 0., 0.]]))
E        +    where <function allclose at 0x7fc922f989e0> = np.allclose

astrofix/tests/test_main.py:44: AssertionError
======================================================================== short test summary info =========================================================================
FAILED astrofix/tests/test_main.py::test_fixing_image - assert False
================================================================= 1 failed, 2 passed in 63.92s (0:01:03) =================================================================

Christopher Willmer

**Comment by HengyueZ** [comment]
Hi @cnaw, thanks for your help! I have checked your results and confirmed that it's a little issue with different machine precisions. The difference between your results and mine is typically smaller than 0.1% of the residual of image correction, so I would not worry about it. Do the tests pass now?

Cheers,
Hengyue Zhang

**Comment by cnaw** [comment]
Hi @HengyueZ,
This is the news:
astrofix/tests/test_main.py::test_kernel_construction PASSED
astrofix/tests/test_main.py::test_training_results PASSED
astrofix/tests/test_main.py::test_fixing_image PASSED
Yay!!!
Thanks for digging into this!   
We can close the issue.

Cheers,
Christopher
